name: 'dev e2e test'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run start
          project: ./apps/insight-viewer-dev-e2e
          browser: chrome
