name: 'Deploy insight-viewer on production'

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/insight-viewer-production.yml
      - libs/insight-viewer/**
      - apps/insight-viewer-dev/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKDIR: .
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx export insight-viewer-dev

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CDN_FOR_PRODUCTION_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CDN_FOR_PRODUCTION_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy Docs
        env:
          HOST: insight-viewer.lunit.io
        run: |
          aws s3 sync \
            ./dist/apps/insight-viewer-dev/exported \
            s3://lunit-cdn-for-production-virginia/${HOST} \
            --delete
          aws s3 cp \
            s3://lunit-cdn-for-production-virginia/${HOST} \
            s3://lunit-cdn-for-production-virginia/${HOST} \
            --recursive \
            --exclude "*" \
            --include "index.html" \
            --metadata-directive REPLACE \
            --cache-control no-store,no-cache,must-revalidate \
            --content-type "text/html; charset=utf-8"
